In [15]:
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2025-06-08 18:19:31--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt.1’

input.txt.1         100%[===================>]   1.06M  --.-KB/s    in 0.09s   

2025-06-08 18:19:31 (12.2 MB/s) - ‘input.txt.1’ saved [1115394/1115394]



In [16]:
with open('input.txt','r',encoding='utf-8') as f:
  text=f.read()

In [17]:
print("Length of Tiny shakesphear is ",len(text))

Length of Tiny shakesphear is  1115394


In [18]:
print(text[:986])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst 


In [19]:
chars=sorted(list(set(text)))
vocab_size=len(chars)
print(''.join(chars))
print("No of char ",vocab_size)



 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
No of char  65


In [20]:
stoi={}
itos={}

for i,ch in enumerate(chars):
  stoi[ch]=i
  itos[i]=ch

encode=lambda s:[stoi[ch] for ch in s ]
decode=lambda l:''.join(itos[i] for i in l)

print(encode("Udayyy says Hi"))
print(decode(encode("Udayyy says Hi")))


[33, 42, 39, 63, 63, 63, 1, 57, 39, 63, 57, 1, 20, 47]
Udayyy says Hi


In [21]:
import torch

data=torch.tensor(encode(text),dtype=torch.long)

In [22]:
print(data.shape,data.dtype)
print(data[:1000])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [38]:
n=int(0.9*len(data))

train=data[:n]
val=data[n:]

In [39]:
blockSize=8

train[:blockSize+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [40]:
x=train[:blockSize]
y=train[1:blockSize+1]

for t in range(blockSize):
  context=x[:t+1]
  target=y[t]

  print(f"for context {context} target is {target}")

for context tensor([18]) target is 47
for context tensor([18, 47]) target is 56
for context tensor([18, 47, 56]) target is 57
for context tensor([18, 47, 56, 57]) target is 58
for context tensor([18, 47, 56, 57, 58]) target is 1
for context tensor([18, 47, 56, 57, 58,  1]) target is 15
for context tensor([18, 47, 56, 57, 58,  1, 15]) target is 47
for context tensor([18, 47, 56, 57, 58,  1, 15, 47]) target is 58


In [42]:
torch.manual_seed(1337)
blockSize=8
batchSize=4

def getBatch(split):
  data=train if split=='train' else val

  idx=torch.randint(len(data)-blockSize,(batchSize,))
  x=torch.stack([data[i:i+blockSize] for i in idx])
  y=torch.stack([data[i+1:i+blockSize+1] for i in idx])

  return x,y

xb,yb=getBatch('train')

print("input:")
print(xb.shape)
print(xb)
print()
print("target:")
print(yb.shape)
print(yb)



input:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])

target:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])


In [48]:
import torch
import torch.nn as nn
from torch.nn import functional as F

torch.manual_seed(1337)

class BigramLanguagemodel(nn.Module):

  def __init__(self,vocab_size):
    super().__init__()
    self.token_embedding_table=nn.Embedding(vocab_size,vocab_size)

  def forward(self,idx,targets=None):

    logits=self.token_embedding_table(idx)

    if targets==None:
      loss=None
    else:
      B,T,C=logits.shape
      logits=logits.reshape(B*T,C)
      targets=targets.reshape(B*T)

      loss=F.cross_entropy(logits,targets)
    return logits,loss

  def generate(self,idx,max_token):

    for _ in range(max_token):
      logits,loss=self.forward(idx)

      logits=logits[:,-1,:]

      prob=F.softmax(logits,dim = -1)

      idx_next=torch.multinomial(prob,num_samples=1)

      idx=torch.cat((idx,idx_next),dim=1)

    return idx

m=BigramLanguagemodel(vocab_size)
logits,loss=m(xb,yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx=torch.zeros(1,1,dtype=torch.long),max_token=100)[0].tolist()))


torch.Size([32, 65])
tensor(4.8786, grad_fn=<NllLossBackward0>)

Sr?qP-QWktXoL&jLDJgOLVz'RIoDqHdhsV&vLLxatjscMpwLERSPyao.qfzs$Ys$zF-w,;eEkzxjgCKFChs!iWW.ObzDnxA Ms$3
